kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "不默，而生"

author: "ethanliao"
atom-baseurl: "http://postdev.net/"
url: "http://postdev.net/"
disqus: "ethanliao"
baseurl: ""


navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

